[package]
name = "build-assets"
version = "0.2.2"
edition = "2021"

[features]
default = ["ned", "osm"]
ned = []
osm = []

[dependencies]
anyhow = "1.0"
flatgeobuf = "5.0.0"
geo-types = "0.7.13"
geojson = "0.24.1"
geozero = "0.14.0"
reqwest = { version = "0.12", features = [
    "blocking",
    "rustls-tls",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
zip = "7.0"
zstd = "0.13.2"
