[package]
name = "spatialtime"
version = "0.3.0"
edition = "2021"
authors = ["Brian Moran <dev@moran.network>"]
license = "MIT"
description = "A simple library to lookup longitude + latitude pairs, using flatgeobufs."
readme = "../README.md"
homepage = "https://github.com/moranbw/spatialtime"
repository = "https://github.com/moranbw/spatialtime"
keywords = ["time", "timezone", "geospatial", "coordinates", "gps"]
categories = ["date-and-time"]

[package.metadata.docs.rs]
features = ["ned", "osm"]

[lib]
name = "spatialtime"
path = "src/lib.rs"

[features]
osm = []
ned = []
rebuild-assets = []

[dependencies]
flatgeobuf = { version = "5.0", default-features = false }
geo = "0.32"
geozero = "0.14.0"
thiserror = "2.0"
zstd = "0.13"

[build-dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = [
    "blocking",
    "rustls-tls",
], default-features = false }
